### ISSUE TITLE
Escribir las épicas e historias de usuario.

### ISSUE THREAD

**Issue by delightfulagony** [NoteGramBot/NoteGram#10]
El problema a resolver sería poder anotar cosas fácilmente y poder compartir esas anotaciones con otras personas.

Creo que deberíamos definir qué usuarios tenemos y una vez tengamos eso escribir las distintas épicas.

**Comment by delightfulagony** [comment]
[Este artículo que compartió JJ ](https://www.altexsoft.com/blog/uxdesign/a-complete-guide-to-user-story-mapping-process-tips-advantages-and-use-cases-in-product-management/) habla del proceso de escribir estas historias y lo divide en 5 partes:

* Objetivos del producto
* Usuarios del producto
* Ideas y Principios
* La **gran** historia del producto paso por paso (No sé muy bien qué es eso)
* Los detalles del software que se puede construir

**Comment by murcian0** [comment]
Después me leeré el articulo.
Estoy un poco hecho un lio con esto de las épicas y las historias pero seguimos para delante.
Podemos aprovechar: [Diseño_Funcional.md](https://github.com/NoteGramBot/NoteGram/blob/master/docs/Dise%C3%B1o_Funcional.md) ,que ha hecho @igponce.
Con todo el respeto, creo que el Diseño Funcional es contrario a la metodología Ágil (corregidme si me equivoco por favor), pero podemos aprovecharlo de cara a mañana tener desarrollado el objetivo del producto, la épica y la historia de usuario.
En cuanto a las historias de usuario, si no he entendido mal nuestra idea, solo tenemos un tipo de usuario, ¿no? Eso debería simplificar las cosas.

**Comment by delightfulagony** [comment]
@murcian0 Creo que depende de como queramos enfocarlo, pero que podemos tener más de un usuario, por ejemplo podemos tener un usuario final  que quiera anotar cosas, también un "sysadmin" del bot que también necesitará unas herramientas de configuración/mantenimiento del software desplegado, si modularizamos y dividimos en back-end/front-end podemos tener también un usuario que interactúe con la API o la librería de back-end directamente, etc.

**Comment by delightfulagony** [comment]
@delightfulagony Nosotros mismo podemos ser "usuarios" de perfil más técnico del módulo de back-end cuando estemos trabajando con la API de telegram para hacer la interfaz, si una persona quiere desplegar también este bot en [matrix] por ejemplo sería un usuario más técnico también pero no deja de ser un usuario del software

**Comment by delightfulagony** [comment]
He abierto [un tablero](https://github.com/NoteGramBot/NoteGram/projects/2) para escribir esto de las historias de usuario (si se prefiere otra estrategia sin problema). 

De momento no voy a añadir nada más a éste hasta que haya un feedback por parte del grupo y se consensúe si se quiere hacer de esta forma o de otra, cuando pueda cada une que comente/reaccione al issue 😊.

**Comment by delightfulagony** [comment]
Me respondo yo sólo para que quede aquí guardado, tras preguntar respecto a los distintos usuarios JJ dice:

JJ, [24.02.21 17:26]
En realidad, las épicas son sólo de cara al usuario. Los detalles de implementación son algo que se deja para issues con programadores como usuario

JJ, [24.02.21 17:27]
Dividir en módulos debe ser posterior a las épicas y las historias de usuario, en todo caso.

**Comment by igponce** [comment]
> JJ, [24.02.21 17:26]
> En realidad, las épicas son sólo de cara al usuario. Los detalles de implementación son algo que se deja para issues con programadores como usuario

Una épica viene a ser entonces más o menos un criterio de aceptación.
Si se ha implementado la épica, el stakejolder te debería aceptar el trabajo.
Son bastante aspiracionales y de alto nivel "quiero escribir notas desde Telegram".
