### ISSUE TITLE
Arquitectura del bot. Tiene que tener "log" para pasar a la siguiente fase.

### ISSUE THREAD

**Issue by igponce** [NoteGramBot/NoteGram#11]

**Comment by igponce** [comment]
Posibilidades de arquitectura

Algunas ideas sobre la arquitectura.

Opción 1: Monolito usando logs como "base de datos"

![imagen](https://user-images.githubusercontent.com/34993/109225665-dcb05500-77bd-11eb-8efc-c0a29829efe7.png)

Estamos en 2021 - un monolito no es tan sencillo de gestionar usando nubes, y logs.
Y dentro de una llamada a una API no deberíamos pasar demasiado tiempo.
Nos pueden penalizar, o deshabilitar las llamadas por eso mismo.

Opción 2: tener "desacoplado" el núcleo del bot de Telegram.

![imagen](https://user-images.githubusercontent.com/34993/109225485-9c50d700-77bd-11eb-8e48-fa1d0e710f6b.png)

La principal ventaja es que aislamos los tres componentes: envío, recepción, y "chicha" con el log.
Eso nos deja crecer de forma sencilla si hace falta.
La desventaja es que pasamos de pegarnos con Telegram en entrada y salida a pegarnos con Kafka o el servicio que sea. Otro componente más.

No he detallado el storage.
Puede ser una BBDD, ficheros, o un topic de Kafka para cada usuario.

**Comment by delightfulagony** [comment]
## Logging
Go dispone de la biblioteca ['log'](https://golang.org/pkg/log) que es sencilla pero cumple su trabajo. Yo abogaría por usar ésta y, en caso de vernos en la necesidad de un logging más complejo, migrar a una que disponga de más funcionalidades: cuando lleguemos a ese río cruzaremos ese puente.

## Arquitectura
Yo soy partidario de la segunda opción, con el núcleo desacoplado de la interacción con TG, es más modular y creo que permite exprimir mejor el paralelismo del que hace gala Go.

## Almacenamiento de los datos
Respecto al uso de Kafka, es una tecnología que por lo que entiendo su caso de uso principal es el de entornos en los cuales se genera una gran cantidad de datos a cada segundo, creo que no es el caso de nuestro proyecto. 
Es una tecnología nueva para mí y puedo estarme equivocando, pero no puedo evitar sentir que el uso de kafka en el proyecto supone un poco de 'over-engineering' y, quizá por costumbre, creo que sería más adecuado usar una BBDD.

Teniendo en cuenta que las notas están asociadas a un usuario/grupo y que en principio al trabajar con la petición de un usuario/grupo se trabajará siempre con notas de las que ese usuario/grupo es "dueño"; creo que una BBDD relacional podría suplir nuestras necesidades.

**Comment by igponce** [comment]
Issue cerrado -> Decisión de arquitectura tomada y reflejada en Readme.md
