### ISSUE TITLE
[Propuesta] Crear una issue por cada hito del curso

### ISSUE THREAD

**Issue by delightfulagony** [NoteGramBot/NoteGram#12]
He pensado que podría ser buena idea crear una issue y añadirla al kanban principal del proyecto por cada hito del curso, así podrían discutirse en ésta todos los aspectos del hito en sí, tener claro el '¿qué hay que hacer?' y nos permitiría marcar como cerrado el issue cuando se hayan completado todas las tareas asociadas, reabrirlo en caso de que surgieran nuevas cosas que hacer respecto de ese issue y en general tener una visión clara de nuestro progreso y del 'backlog' del curso.

**Comment by murcian0** [comment]
Me parece que sería la mejor práctica en este caso.

**Comment by igponce** [comment]
:100: 👍 👍 👍 👍 👍 👍 👍 👍 👍

**Comment by igponce** [comment]
Yo cerraría este issue. Aprobado pro mayoría ¿no?

**Comment by delightfulagony** [comment]
Hemos optado por en lugar de issues usar milestones (que es más o menos lo mismo pero con la posibilidad de asociar varios issues).
Cierro la issue, en cualquier caso si alguien tiene algo que añadir que reabra el issue 👏👏
