### ISSUE TITLE
HITO 4: Reformular las épicas de usuario incluyendo a personas

### ISSUE THREAD

**Issue by delightfulagony** [NoteGramBot/NoteGram#18]
Crear agil.yml dónde incluyamos las personas a las que va dirigida la aplicación con el siguiente formato:
```
personas:
    - Juan Rueda
    - Pilar Gómez
```

**Comment by igponce** [comment]
Algo de información sobre las personas / personajes:

Juan Rueda
   Usuario sin privilegios.
   Quiere tomar notas de lo que comenta en Telegram para poder tenerlo como referencia.
   Le interesa sobre todo links a otros sitios mencionados en TG.

Pilar Gómez
   Administradora de un grupo de Telegram que comparte con otras compañeras.
   Quiere tomar nota de algunas cosas que cuentan con sus amigas en el grupo para recordarlas después.
