### ISSUE TITLE
HITO8 - Decidir linter a usar para Hito

### ISSUE THREAD

**Issue by igponce** [NoteGramBot/NoteGram#23]
Hay que indicar en el fichero agil.yaml el linter que vamos a usar.
Tenemos algunos linter disponibles para GO.

Proponemos en los comentarios linters y votamos 👎 👍

**Comment by delightfulagony** [comment]
@igponce ¿Pueden usarse intercambiablemente sin que haya diferencias entre ellos?

**Comment by igponce** [comment]
Hay diferencias.

- La principal es que `go vet` viene con el sistema, y el otro hay que instalarlo.
- `golangci-linter` es más exhaustivo. "Caza" más cosas que `go vet` (complejidad ciclomática por ejemplo).

Acabo de ver que golangci-linter también puede usar `go vet` por debajo: https://golangci-lint.run/usage/linters/

**Comment by igponce** [comment]
Votación: USAMOS [go vet](https://golang.org/cmd/vet/) - Linter por defecto disponible en el sistema. No hay que instalar nada.

**Comment by igponce** [comment]
Votación: USAMOS [golangci-linter](https://github.com/golangci/golangci-lint) - Linter pensado para formar parte de un entorno de integración contínua.

**Comment by igponce** [comment]
Resultado votación: go vet 
Actualizando agil.yaml
