### ISSUE TITLE
@igponce eres un crack 💚💯

### ISSUE THREAD

**Issue by murcian0** [NoteGramBot/NoteGram#3]
Con lo que @igponce ha añadido en Projects, creo que ya estamos listos para la clase de hoy.
Envio este Issue en parte a ver si aparece ahi jeje just testing
Solo faltaría hacer un tag🔖 y pull request a JJ/curso-tdd/proyectos.md actualizando nuestro proyecto.

**Comment by igponce** [comment]
Reabierto. Todos los issues tienen que tener ahora un commit.
