### ISSUE TITLE
Diseñar la estructura del código: clases, capas...

### ISSUE THREAD

**Issue by igponce** [NoteGramBot/NoteGram#31]
Hay que diseñar las capas / partes que tiene el código.
Así se puede separar la funcionalidad y que no esté todo enmarañao, y también se puede distribuir el trabajo.

**Comment by igponce** [comment]
En mi opinión hay 2 o como mucho 3 capas:
- Interfaz con Telegram
- Interfaz con la Base de Datos mongdb
- Lógica interna del programa (core/kernel/ o como le llamemos)

Hay que tener en cuenta los "contratos" entre las partes.
Es decir, cómo se hablan entre ellos y cómo se llaman los unos a los otros.

**Comment by delightfulagony** [comment]
Me parece buena estructura :+1:

**Comment by igponce** [comment]
Pendiente de cierre con un commit.
