### ISSUE TITLE
Añadido Pull Request en JJ/curso-TDD/proyectos.md

### ISSUE THREAD

**Issue by murcian0** [NoteGramBot/NoteGram#5]
💚 Actualización v1.0.1 -> Planteamiento Inicial del Proyecto

Cambio de nombre organización, repositorio y proyecto:
botTDD/bot-Telegram -> NoteGramBot/NoteGram
[bot-Telegram] -> [NoteGram]

**Comment by igponce** [comment]
Reabierto. Todos los issues tienen que tener ahora un commit.
