### ISSUE TITLE
GO. Acordar versión a instalar, y usar todos la misma para no tener problemas. (Usar GO 1.16)

### ISSUE THREAD

**Issue by igponce** [NoteGramBot/NoteGram#6]
En teoría no tendríamos que tener problemas con GO - se supone que todo el código es compatible hacia atras desde la versión 1 en adelante **peero** siempre puede haber algo (deprecation warnings y esas cosas)... o que alguien esté usando features de una versión más adelantada que no esté contemplada.

**Comment by murcian0** [comment]
En mi opinión, última versión de GO. Ya nos pelearemos con los problemas si surgen.
Yo abriría otro Issue en cuanto al tema Bot. La verdad que no se ni como habéis implementado el de GitHub que tenemos en nuestro Telegram 😄 Si alguien puede y le apetece explicarme un poco os lo agradecería, creo que algunos pilotáis de este tema.

**Comment by igponce** [comment]
@murcian0 - He abierto otro issue para meter los requisitos técnicos de montar todo este tinglao.
